/*
=============================================================
 DRAINGUARD
 Autonomous Robotic System for Stormwater Drain Inspection
 and Blockage Detection

 Hardware:
 - Seeed Studio XIAO ESP32S3 Sense
 - Camera
 - BME280
 - Water/Moisture Sensor
 - MQ Gas Sensor
 - Distance Sensor
 - Battery Monitor
 - Motor Driver
 - Trained Edge Impulse ML Model

 Features:
 - Custom Web Dashboard
 - Camera Snapshot Feed
 - ML Blockage Detection
 - Sensor Monitoring
 - Robot Control
 - Automatic Hazard Alerts
 - Live Telemetry API

=============================================================
*/

#include <WiFi.h>
#include <WebServer.h>
#include <Wire.h>
#include "esp_camera.h"

#include <Adafruit_BME280.h>
#include <Adafruit_Sensor.h>

/*
=============================================================
 EDGE IMPULSE MODEL

 Replace this filename with the header generated by
 your downloaded Edge Impulse Arduino library.

 Example:

 #include <DrainGuard_Blockage_inferencing.h>

=============================================================
*/

#include <your_drainguard_inferencing.h>


// ============================================================
// WIFI SETTINGS
// ============================================================

const char* ssid = "YOUR_WIFI_NAME";
const char* password = "YOUR_WIFI_PASSWORD";

WebServer server(80);


// ============================================================
// XIAO ESP32S3 SENSE CAMERA PINS
// ============================================================

#define PWDN_GPIO_NUM    -1
#define RESET_GPIO_NUM   -1

#define XCLK_GPIO_NUM    10
#define SIOD_GPIO_NUM    40
#define SIOC_GPIO_NUM    39

#define Y9_GPIO_NUM      48
#define Y8_GPIO_NUM      11
#define Y7_GPIO_NUM      12
#define Y6_GPIO_NUM      14
#define Y5_GPIO_NUM      16
#define Y4_GPIO_NUM      18
#define Y3_GPIO_NUM      17
#define Y2_GPIO_NUM      15

#define VSYNC_GPIO_NUM   38
#define HREF_GPIO_NUM    47
#define PCLK_GPIO_NUM    13


// ============================================================
// I2C PINS
// ============================================================

#define I2C_SDA 5
#define I2C_SCL 6


// ============================================================
// SENSOR PINS
// ============================================================

// Change these according to your final wiring.

#define MOISTURE_PIN 1
#define GAS_PIN      2
#define BATTERY_PIN  3


// ============================================================
// ULTRASONIC SENSOR
// ============================================================

#define TRIG_PIN 4
#define ECHO_PIN 7


// ============================================================
// MOTOR DRIVER PINS
// ============================================================

// IMPORTANT:
// Assign according to your available GPIO pins
// and motor driver wiring.

#define MOTOR_LEFT_IN1   8
#define MOTOR_LEFT_IN2   9

#define MOTOR_RIGHT_IN1  41
#define MOTOR_RIGHT_IN2  42


// ============================================================
// BME280
// ============================================================

Adafruit_BME280 bme;


// ============================================================
// DEVICE STATE
// ============================================================

String robotStatus = "STANDBY";
String movement = "STOP";


// ============================================================
// SENSOR DATA
// ============================================================

float temperature = 0;
float humidity = 0;
float pressure = 0;

int moistureLevel = 0;
int gasValue = 0;

float distanceCM = 0;

float batteryVoltage = 0;
int batteryPercent = 0;


// ============================================================
// AI DATA
// ============================================================

String blockageLevel = "SCANNING";
String blockageStatus = "WAITING";
float aiConfidence = 0;

String detectedClass = "NONE";

unsigned long lastInference = 0;

const unsigned long INFERENCE_INTERVAL = 2500;


// ============================================================
// CAMERA INITIALIZATION
// ============================================================

bool initCamera() {

  camera_config_t config;

  config.ledc_channel = LEDC_CHANNEL_0;
  config.ledc_timer = LEDC_TIMER_0;

  config.pin_d0 = Y2_GPIO_NUM;
  config.pin_d1 = Y3_GPIO_NUM;
  config.pin_d2 = Y4_GPIO_NUM;
  config.pin_d3 = Y5_GPIO_NUM;
  config.pin_d4 = Y6_GPIO_NUM;
  config.pin_d5 = Y7_GPIO_NUM;
  config.pin_d6 = Y8_GPIO_NUM;
  config.pin_d7 = Y9_GPIO_NUM;

  config.pin_xclk = XCLK_GPIO_NUM;
  config.pin_pclk = PCLK_GPIO_NUM;

  config.pin_vsync = VSYNC_GPIO_NUM;
  config.pin_href = HREF_GPIO_NUM;

  config.pin_sccb_sda = SIOD_GPIO_NUM;
  config.pin_sccb_scl = SIOC_GPIO_NUM;

  config.pin_pwdn = PWDN_GPIO_NUM;
  config.pin_reset = RESET_GPIO_NUM;

  config.xclk_freq_hz = 20000000;

  config.pixel_format = PIXFORMAT_JPEG;

  if(psramFound()) {

    config.frame_size = FRAMESIZE_QVGA;
    config.jpeg_quality = 12;
    config.fb_count = 2;

  } else {

    config.frame_size = FRAMESIZE_QQVGA;
    config.jpeg_quality = 15;
    config.fb_count = 1;
  }

  esp_err_t err = esp_camera_init(&config);

  if(err != ESP_OK) {

    Serial.printf(
      "Camera initialization failed: 0x%x\n",
      err
    );

    return false;
  }

  Serial.println("Camera initialized successfully");

  return true;
}


// ============================================================
// READ BME280
// ============================================================

void readBME280() {

  temperature =
    bme.readTemperature();

  humidity =
    bme.readHumidity();

  pressure =
    bme.readPressure() / 100.0F;
}


// ============================================================
// READ MOISTURE
// ============================================================

void readMoisture() {

  int rawValue =
    analogRead(MOISTURE_PIN);

  moistureLevel =
    map(
      rawValue,
      0,
      4095,
      100,
      0
    );

  moistureLevel =
    constrain(
      moistureLevel,
      0,
      100
    );
}


// ============================================================
// READ GAS SENSOR
// ============================================================

void readGas() {

  gasValue =
    analogRead(GAS_PIN);
}


// ============================================================
// READ BATTERY
// ============================================================

void readBattery() {

  int raw =
    analogRead(BATTERY_PIN);

  /*
   Adjust multiplier according
   to your voltage divider.
  */

  batteryVoltage =
    ((float)raw / 4095.0) *
    3.3 *
    2.0;

  batteryPercent =
    map(
      (int)(batteryVoltage * 100),
      330,
      420,
      0,
      100
    );

  batteryPercent =
    constrain(
      batteryPercent,
      0,
      100
    );
}


// ============================================================
// READ ULTRASONIC SENSOR
// ============================================================

void readDistance() {

  digitalWrite(
    TRIG_PIN,
    LOW
  );

  delayMicroseconds(2);

  digitalWrite(
    TRIG_PIN,
    HIGH
  );

  delayMicroseconds(10);

  digitalWrite(
    TRIG_PIN,
    LOW
  );

  long duration =
    pulseIn(
      ECHO_PIN,
      HIGH,
      30000
    );

  if(duration > 0) {

    distanceCM =
      duration * 0.0343 / 2.0;
  }
}


// ============================================================
// READ ALL SENSORS
// ============================================================

void updateSensors() {

  readBME280();

  readMoisture();

  readGas();

  readBattery();

  readDistance();
}


// ============================================================
// ROBOT MOVEMENT
// ============================================================

void stopRobot() {

  digitalWrite(MOTOR_LEFT_IN1, LOW);
  digitalWrite(MOTOR_LEFT_IN2, LOW);

  digitalWrite(MOTOR_RIGHT_IN1, LOW);
  digitalWrite(MOTOR_RIGHT_IN2, LOW);

  movement = "STOPPED";
}


void moveForward() {

  digitalWrite(MOTOR_LEFT_IN1, HIGH);
  digitalWrite(MOTOR_LEFT_IN2, LOW);

  digitalWrite(MOTOR_RIGHT_IN1, HIGH);
  digitalWrite(MOTOR_RIGHT_IN2, LOW);

  movement = "FORWARD";
}


void moveBackward() {

  digitalWrite(MOTOR_LEFT_IN1, LOW);
  digitalWrite(MOTOR_LEFT_IN2, HIGH);

  digitalWrite(MOTOR_RIGHT_IN1, LOW);
  digitalWrite(MOTOR_RIGHT_IN2, HIGH);

  movement = "REVERSE";
}


void turnLeft() {

  digitalWrite(MOTOR_LEFT_IN1, LOW);
  digitalWrite(MOTOR_LEFT_IN2, HIGH);

  digitalWrite(MOTOR_RIGHT_IN1, HIGH);
  digitalWrite(MOTOR_RIGHT_IN2, LOW);

  movement = "LEFT";
}


void turnRight() {

  digitalWrite(MOTOR_LEFT_IN1, HIGH);
  digitalWrite(MOTOR_LEFT_IN2, LOW);

  digitalWrite(MOTOR_RIGHT_IN1, LOW);
  digitalWrite(MOTOR_RIGHT_IN2, HIGH);

  movement = "RIGHT";
}


// ============================================================
// EDGE IMPULSE IMAGE BUFFER
// ============================================================

camera_fb_t *aiFrame = NULL;


// ============================================================
// CAPTURE IMAGE FOR AI
// ============================================================

bool cameraCaptureForAI(
  size_t offset,
  size_t length,
  float *out_ptr
) {

  if(aiFrame == NULL) {
    return false;
  }

  size_t pixelIndex =
    offset * 3;

  for(
    size_t i = 0;
    i < length;
    i++
  ) {

    if(
      pixelIndex + 2 >=
      aiFrame->len
    ) {
      return false;
    }

    uint8_t r =
      aiFrame->buf[pixelIndex];

    uint8_t g =
      aiFrame->buf[pixelIndex + 1];

    uint8_t b =
      aiFrame->buf[pixelIndex + 2];

    out_ptr[i] =
      (r << 16) |
      (g << 8) |
      b;

    pixelIndex += 3;
  }

  return true;
}


// ============================================================
// RUN AI MODEL
// ============================================================

void runBlockageAI() {

  if(
    millis() - lastInference <
    INFERENCE_INTERVAL
  ) {
    return;
  }

  lastInference = millis();

  /*
   NOTE:

   A production Edge Impulse image model normally
   requires a correctly formatted RGB buffer.

   Depending on your exported model, the image capture
   and conversion code may differ.

   This section provides the integration architecture.
  */

  Serial.println(
    "Running blockage AI..."
  );


  /*
   ----------------------------------------------------
   YOUR MODEL-SPECIFIC INFERENCE CODE GOES HERE
   ----------------------------------------------------

   Example conceptual workflow:

   1. Capture camera frame
   2. Convert frame to RGB888
   3. Resize to EI_CLASSIFIER_INPUT_WIDTH
      x EI_CLASSIFIER_INPUT_HEIGHT
   4. Create signal_t
   5. Call run_classifier()
   6. Read classification results

   Example:

   signal_t signal;
   ei_impulse_result_t result;

   signal.total_length =
     EI_CLASSIFIER_DSP_INPUT_FRAME_SIZE;

   signal.get_data =
     &cameraCaptureForAI;

   EI_IMPULSE_ERROR res =
     run_classifier(
       &signal,
       &result,
       false
     );

   ----------------------------------------------------
  */


  /*
   TEMPORARY SENSOR + DEMO LOGIC

   Replace this section with results
   from your trained ML model.
  */

  if(distanceCM < 10) {

    detectedClass =
      "FULL_BLOCKAGE";

    blockageLevel =
      "CRITICAL";

    blockageStatus =
      "Drain Severely Blocked";

    aiConfidence =
      92.0;

  }
  else if(distanceCM < 25) {

    detectedClass =
      "HIGH_BLOCKAGE";

    blockageLevel =
      "HIGH";

    blockageStatus =
      "Major Obstruction Detected";

    aiConfidence =
      87.0;

  }
  else if(distanceCM < 50) {

    detectedClass =
      "MEDIUM_BLOCKAGE";

    blockageLevel =
      "MEDIUM";

    blockageStatus =
      "Partial Obstruction";

    aiConfidence =
      81.0;

  }
  else {

    detectedClass =
      "CLEAR";

    blockageLevel =
      "LOW";

    blockageStatus =
      "Drain Passage Appears Clear";

    aiConfidence =
      95.0;
  }


  // --------------------------------------------------
  // ADDITIONAL HAZARD LOGIC
  // --------------------------------------------------

  if(gasValue > 2500) {

    robotStatus =
      "GAS HAZARD DETECTED";

  }
  else if(blockageLevel == "CRITICAL") {

    robotStatus =
      "CRITICAL BLOCKAGE";

  }
  else if(batteryPercent < 20) {

    robotStatus =
      "LOW BATTERY";

  }
  else {

    robotStatus =
      "INSPECTING";
  }
}


// ============================================================
// LIVE CAMERA IMAGE
// ============================================================

void handleCamera() {

  camera_fb_t *fb =
    esp_camera_fb_get();

  if(!fb) {

    server.send(
      500,
      "text/plain",
      "Camera capture failed"
    );

    return;
  }

  server.sendHeader(
    "Content-Type",
    "image/jpeg"
  );

  server.sendHeader(
    "Content-Length",
    String(fb->len)
  );

  server.send_P(
    200,
    "image/jpeg",
    (const char*)fb->buf,
    fb->len
  );

  esp_camera_fb_return(fb);
}


// ============================================================
// TELEMETRY JSON
// ============================================================

void handleTelemetry() {

  updateSensors();

  runBlockageAI();

  String json = "{";

  json +=
    "\"temperature\":" +
    String(temperature, 1) + ",";

  json +=
    "\"humidity\":" +
    String(humidity, 1) + ",";

  json +=
    "\"pressure\":" +
    String(pressure, 1) + ",";

  json +=
    "\"moisture\":" +
    String(moistureLevel) + ",";

  json +=
    "\"gas\":" +
    String(gasValue) + ",";

  json +=
    "\"distance\":" +
    String(distanceCM, 1) + ",";

  json +=
    "\"battery\":" +
    String(batteryPercent) + ",";

  json +=
    "\"blockageLevel\":\"" +
    blockageLevel + "\",";

  json +=
    "\"detectedClass\":\"" +
    detectedClass + "\",";

  json +=
    "\"blockageStatus\":\"" +
    blockageStatus + "\",";

  json +=
    "\"confidence\":" +
    String(aiConfidence, 1) + ",";

  json +=
    "\"robotStatus\":\"" +
    robotStatus + "\",";

  json +=
    "\"movement\":\"" +
    movement + "\"";

  json += "}";

  server.send(
    200,
    "application/json",
    json
  );
}


// ============================================================
// ROBOT CONTROL API
// ============================================================

void handleControl() {

  String command =
    server.arg("cmd");

  if(command == "forward") {

    moveForward();

  }
  else if(command == "backward") {

    moveBackward();

  }
  else if(command == "left") {

    turnLeft();

  }
  else if(command == "right") {

    turnRight();

  }
  else {

    stopRobot();
  }

  server.send(
    200,
    "text/plain",
    movement
  );
}


// ============================================================
// CUSTOM WEB DASHBOARD
// ============================================================

const char INDEX_HTML[] PROGMEM = R"rawliteral(

<!DOCTYPE html>

<html>

<head>

<meta
name="viewport"
content="width=device-width, initial-scale=1.0">

<title>DrainGuard Control Center</title>

<style>

*{
box-sizing:border-box;
}

body{
margin:0;
font-family:
Arial,
Helvetica,
sans-serif;

background:#f3f4f6;
color:#111827;
}

header{

background:
linear-gradient(
135deg,
#111827,
#1f2937
);

color:white;

padding:22px 35px;

display:flex;

justify-content:
space-between;

align-items:center;

flex-wrap:wrap;
}

header h1{

margin:0;

font-size:28px;
}

header p{

margin:6px 0 0;

color:#9ca3af;
}

.status{

padding:10px 16px;

background:#dcfce7;

color:#166534;

border-radius:30px;

font-weight:bold;
}

.container{

padding:25px;

max-width:1600px;

margin:auto;
}

.top-grid{

display:grid;

grid-template-columns:
1.4fr
1fr;

gap:20px;
}

.camera-card{

background:white;

border-radius:16px;

padding:18px;

box-shadow:
0 8px 30px
rgba(0,0,0,.08);
}

.camera-card h2{

margin-top:0;
}

.camera{

width:100%;

min-height:350px;

object-fit:cover;

background:#111827;

border-radius:12px;
}

.ai-panel{

background:
linear-gradient(
135deg,
#111827,
#374151
);

color:white;

border-radius:16px;

padding:25px;

box-shadow:
0 8px 30px
rgba(0,0,0,.12);
}

.ai-value{

font-size:42px;

font-weight:bold;

color:#f97316;

margin:15px 0;
}

.confidence{

font-size:22px;

color:#86efac;
}

.sensor-grid{

display:grid;

grid-template-columns:
repeat(
auto-fit,
minmax(180px,1fr)
);

gap:15px;

margin-top:22px;
}

.card{

background:white;

border-radius:14px;

padding:18px;

box-shadow:
0 5px 20px
rgba(0,0,0,.06);

border-left:
5px solid #2563eb;
}

.card .label{

color:#6b7280;

font-size:14px;
}

.card .value{

font-size:27px;

font-weight:bold;

margin-top:8px;

color:#111827;
}

.control-panel{

margin-top:22px;

background:white;

border-radius:16px;

padding:22px;

box-shadow:
0 5px 20px
rgba(0,0,0,.06);
}

button{

border:none;

padding:14px 22px;

margin:5px;

border-radius:10px;

font-size:16px;

font-weight:bold;

cursor:pointer;

background:#2563eb;

color:white;
}

button:hover{

transform:scale(1.03);
}

.stop{

background:#dc2626;
}

.warning{

color:#dc2626;
font-weight:bold;
}

@media(max-width:900px){

.top-grid{

grid-template-columns:1fr;
}

.camera{

min-height:250px;
}

}

</style>

</head>

<body>

<header>

<div>

<h1>
🛡️ DrainGuard Control Center
</h1>

<p>
Autonomous Stormwater Drain Inspection
and Blockage Detection System
</p>

</div>

<div
class="status"
id="robotStatus">

CONNECTING...

</div>

</header>


<div class="container">


<!-- CAMERA + AI -->

<div class="top-grid">


<div class="camera-card">

<h2>
📹 Live Drain Inspection Camera
</h2>

<img
id="camera"
class="camera"
src="/camera">

</div>


<div class="ai-panel">

<h2>
🤖 AI Blockage Analysis
</h2>

<div>
Detected Class
</div>

<div
class="ai-value"
id="blockage">

SCANNING

</div>

<div
id="blockageStatus">

Waiting for analysis...

</div>

<br>

<div class="confidence">

Confidence:
<span id="confidence">
0
</span>%

</div>

</div>

</div>


<!-- SENSOR CARDS -->

<div class="sensor-grid">


<div class="card">

<div class="label">
🌡 Temperature
</div>

<div
class="value"
id="temperature">

--

</div>

</div>


<div class="card">

<div class="label">
💧 Humidity
</div>

<div
class="value"
id="humidity">

--

</div>

</div>


<div class="card">

<div class="label">
📊 Pressure
</div>

<div
class="value"
id="pressure">

--

</div>

</div>


<div class="card">

<div class="label">
🌊 Water / Moisture
</div>

<div
class="value"
id="moisture">

--

</div>

</div>


<div class="card">

<div class="label">
☁️ Gas Reading
</div>

<div
class="value"
id="gas">

--

</div>

</div>


<div class="card">

<div class="label">
📏 Obstacle Distance
</div>

<div
class="value"
id="distance">

--

</div>

</div>


<div class="card">

<div class="label">
🔋 Battery
</div>

<div
class="value"
id="battery">

--

</div>

</div>


<div class="card">

<div class="label">
🚙 Movement
</div>

<div
class="value"
id="movement">

STOP

</div>

</div>

</div>


<!-- CONTROL -->

<div class="control-panel">

<h2>
🎮 Manual Robot Control
</h2>

<div>

<button
onclick="controlRobot('forward')">

⬆ Forward

</button>

<br>

<button
onclick="controlRobot('left')">

⬅ Left

</button>

<button
class="stop"
onclick="controlRobot('stop')">

■ STOP

</button>

<button
onclick="controlRobot('right')">

Right ➡

</button>

<br>

<button
onclick="controlRobot('backward')">

⬇ Reverse

</button>

</div>

</div>

</div>


<script>


function controlRobot(cmd){

fetch(
"/control?cmd=" + cmd
);

}


function updateCamera(){

let camera =
document.getElementById(
"camera"
);

camera.src =
"/camera?ts=" +
Date.now();

}


function updateDashboard(){

fetch("/telemetry")

.then(
response => response.json()
)

.then(
data => {

document.getElementById(
"temperature"
).innerHTML =
data.temperature + " °C";


document.getElementById(
"humidity"
).innerHTML =
data.humidity + " %";


document.getElementById(
"pressure"
).innerHTML =
data.pressure + " hPa";


document.getElementById(
"moisture"
).innerHTML =
data.moisture + " %";


document.getElementById(
"gas"
).innerHTML =
data.gas;


document.getElementById(
"distance"
).innerHTML =
data.distance + " cm";


document.getElementById(
"battery"
).innerHTML =
data.battery + " %";


document.getElementById(
"movement"
).innerHTML =
data.movement;


document.getElementById(
"blockage"
).innerHTML =
data.detectedClass;


document.getElementById(
"blockageStatus"
).innerHTML =
data.blockageStatus;


document.getElementById(
"confidence"
).innerHTML =
data.confidence;


document.getElementById(
"robotStatus"
).innerHTML =
data.robotStatus;

}

)

.catch(
error => {

document.getElementById(
"robotStatus"
).innerHTML =
"CONNECTION ERROR";

}

);

}


setInterval(
updateDashboard,
1500
);


setInterval(
updateCamera,
700
);


updateDashboard();


</script>

</body>

</html>

)rawliteral";


// ============================================================
// ROOT PAGE
// ============================================================

void handleRoot() {

  server.send_P(
    200,
    "text/html",
    INDEX_HTML
  );
}


// ============================================================
// SETUP
// ============================================================

void setup() {

  Serial.begin(115200);

  delay(1000);

  Serial.println();
  Serial.println(
    "================================"
  );

  Serial.println(
    "DRAINGUARD STARTING..."
  );

  Serial.println(
    "================================"
  );


  // ----------------------------------------------------------
  // ANALOG CONFIGURATION
  // ----------------------------------------------------------

  analogReadResolution(12);


  // ----------------------------------------------------------
  // I2C
  // ----------------------------------------------------------

  Wire.begin(
    I2C_SDA,
    I2C_SCL
  );


  // ----------------------------------------------------------
  // SENSOR PINS
  // ----------------------------------------------------------

  pinMode(
    MOISTURE_PIN,
    INPUT
  );

  pinMode(
    GAS_PIN,
    INPUT
  );

  pinMode(
    BATTERY_PIN,
    INPUT
  );


  // ----------------------------------------------------------
  // ULTRASONIC
  // ----------------------------------------------------------

  pinMode(
    TRIG_PIN,
    OUTPUT
  );

  pinMode(
    ECHO_PIN,
    INPUT
  );


  // ----------------------------------------------------------
  // MOTOR PINS
  // ----------------------------------------------------------

  pinMode(
    MOTOR_LEFT_IN1,
    OUTPUT
  );

  pinMode(
    MOTOR_LEFT_IN2,
    OUTPUT
  );

  pinMode(
    MOTOR_RIGHT_IN1,
    OUTPUT
  );

  pinMode(
    MOTOR_RIGHT_IN2,
    OUTPUT
  );

  stopRobot();


  // ----------------------------------------------------------
  // BME280
  // ----------------------------------------------------------

  bool bmeStatus =
    bme.begin(0x76);

  if(!bmeStatus) {

    Serial.println(
      "BME280 not found!"
    );

  } else {

    Serial.println(
      "BME280 connected"
    );
  }


  // ----------------------------------------------------------
  // CAMERA
  // ----------------------------------------------------------

  if(!initCamera()) {

    Serial.println(
      "Camera failed!"
    );

  }


  // ----------------------------------------------------------
  // WIFI
  // ----------------------------------------------------------

  WiFi.mode(
    WIFI_STA
  );

  WiFi.begin(
    ssid,
    password
  );

  Serial.print(
    "Connecting to WiFi"
  );

  unsigned long wifiStart =
    millis();

  while(
    WiFi.status() != WL_CONNECTED
  ) {

    delay(500);

    Serial.print(".");

    if(
      millis() - wifiStart >
      20000
    ) {

      Serial.println(
        "\nWiFi timeout"
      );

      break;
    }
  }


  if(
    WiFi.status() ==
    WL_CONNECTED
  ) {

    Serial.println();

    Serial.println(
      "WiFi Connected!"
    );

    Serial.print(
      "DrainGuard Dashboard: http://"
    );

    Serial.println(
      WiFi.localIP()
    );
  }


  // ----------------------------------------------------------
  // WEB ROUTES
  // ----------------------------------------------------------

  server.on(
    "/",
    HTTP_GET,
    handleRoot
  );


  server.on(
    "/telemetry",
    HTTP_GET,
    handleTelemetry
  );


  server.on(
    "/camera",
    HTTP_GET,
    handleCamera
  );


  server.on(
    "/control",
    HTTP_GET,
    handleControl
  );


  server.begin();

  Serial.println(
    "DrainGuard Web Server Started"
  );
}


// ============================================================
// MAIN LOOP
// ============================================================

void loop() {

  server.handleClient();

  delay(5);
}